### ISSUE TITLE
List targeted websites

### ISSUE THREAD

**Issue by FlorianBruniaux** [MIM-TPZ/scraper#1]
- Linkedin --> OK
- ~Monster~
- Indeed
- ~cidj~ 
- ~Job’n’roll~
- StackOverflow --> OK
- ~JobyPepper~
- ~StudentJob~
- ~Pôle-emploi~
- ~Keljob~
- ~La crème de la crème~
- ChooseyourBoss
- ~Side.co~

**Comment by raphael-batlle** [comment]
Indeed / Linkedin / Chooseyourboss

**Comment by adrienqua** [comment]
Linkedin / Indeed

**Comment by Pierrekompf** [comment]
Linkedin/Indeed

**Comment by Jintarei** [comment]
Linkedin / choose your boss

**Comment by FlorianBruniaux** [comment]
Ok on valide on close
